### ISSUE TITLE
Opening programs behaviour on Windows

### ISSUE THREAD

**Issue by Enchufadoo** [FFMG/myoddweb.piger#42]
Hi, I just installed to try it, when I enter chrome or firefox or iexplore as a command, the url it opens is this one

file:///C:/Program%20Files/myoddweb/Piger/ActionMonitor.exe

Running piger-0.6.16.14.exe and  I'm on Windows 7 64 

Then I tried opening filezilla and I also get an error, I'm assuming that it's because "C:/Program%20Files/myoddweb/Piger/ActionMonitor.exe" is passed as a first argument to any program I open? Because if try to open filezilla.exe like this I get the same error.

**Comment by FFMG** [comment]
This is not really a defect, but rather by design, (you could argue that it is not ideal).

Those scripts are dynamically created, if you create your own script, 

Call it `firefox.lua`

```lua
local browser = "firefox"
am_say( "Starting Google.", 400, 10 );
am_execute( browser, "http://www.google.com/" );
```

And save it in your root command directory, reload the commands and you should be good.

Hope this makes sense.

**Comment by Enchufadoo** [comment]
Oh it was a feature :D... thanks for your response.

**Comment by FFMG** [comment]
I'll change it for the next release, I can see now that it is not ideal... :)

**Comment by FFMG** [comment]
Version [0.7.14](https://github.com/FFMG/myoddweb.piger/releases/latest) now launches *.exes without passing a parameter.

But writing a custom script to launch a browser might be a better option, (to get possible urls, default browsers and so on).

But at least it behaves a bit better now :).

**Comment by Enchufadoo** [comment]
Just tried it, works great
